version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: ciisa_backend
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pmypassword"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql_db
      DB_DATABASE: ciisa_backend
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    ports:
      - "9000:9000"  # PHP-FPM (opcional para debugging)
    networks:
      - laravel_network
    depends_on:
      mysql_db:
        condition: service_healthy  # Espera hasta que MySQL esté listo
    healthcheck:
      test: ["CMD", "./wait-for-mysql.sh"]  # Ruta al script en el contenedor
      interval: 5s
      timeout: 10s
      retries: 5

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public  # Solo montar la carpeta pública
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql_db
    networks:
      - laravel_network

networks:  # ¡Sección faltante!
  laravel_network:
    driver: bridge

volumes:
  mysql_data: